curso-desenvolvimento-web-com-jsf2-master/curso-desenvolvimento-web-com-jsf2-master/ProjetoCursoConfigurandoJPAHibernate/src/com/algaworks/cursojsf2/financeiro/model/Lancamento.java
package com.algaworks.cursojsf2.financeiro.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Lancamento implements Serializable {

	private Integer codigo;
	private TipoLancamento tipo;
	private Pessoa pessoa;
	private String descricao;
	private BigDecimal valor;
	private Date dataVencimento;
	private boolean pago;
	private Date dataPagamento;
	
	public Integer getCodigo() {
		return codigo;
	}
	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}
	public TipoLancamento getTipo() {
		return tipo;
	}
	public void setTipo(TipoLancamento tipo) {
		this.tipo = tipo;
	}
	public Pessoa getPessoa() {
		return pessoa;
	}
	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}
	public String getDescricao() {
		return descricao;
	}
	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}
	public BigDecimal getValor() {
		return valor;
	}
	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}
	public Date getDataVencimento() {
		return dataVencimento;
	}
	public void setDataVencimento(Date dataVencimento) {
		this.dataVencimento = dataVencimento;
	}
	public boolean isPago() {
		return pago;
	}
	public void setPago(boolean pago) {
		this.pago = pago;
	}
	public Date getDataPagamento() {
		return dataPagamento;
	}
	public void setDataPagamento(Date dataPagamento) {
		this.dataPagamento = dataPagamento;
	}
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((codigo == null) ? 0 : codigo.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Lancamento other = (Lancamento) obj;
		if (codigo == null) {
			if (other.codigo != null)
				return false;
		} else if (!codigo.equals(other.codigo))
			return false;
		return true;
	}
	
}

curso-desenvolvimento-web-com-jsf2-master/curso-desenvolvimento-web-com-jsf2-master/ProjetoCursoConfigurandoJPAHibernate/src/com/algaworks/cursojsf2/financeiro/model/Pessoa.java
package com.algaworks.cursojsf2.financeiro.model;

import java.io.Serializable;

public class Pessoa implements Serializable {

	private Integer codigo;
	private String nome;
	
	public Pessoa() {
	}
	
	public Pessoa(Integer codigo, String nome) {
		this.codigo = codigo;
		this.nome = nome;
	}
	
	public Integer getCodigo() {
		return codigo;
	}
	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}
	public String getNome() {
		return nome;
	}
	public void setNome(String nome) {
		this.nome = nome;
	}
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((codigo == null) ? 0 : codigo.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Pessoa other = (Pessoa) obj;
		if (codigo == null) {
			if (other.codigo != null)
				return false;
		} else if (!codigo.equals(other.codigo))
			return false;
		return true;
	}
	
}

curso-desenvolvimento-web-com-jsf2-master/curso-desenvolvimento-web-com-jsf2-master/ProjetoCursoConfigurandoJPAHibernate/src/com/algaworks/cursojsf2/financeiro/model/TipoLancamento.java
package com.algaworks.cursojsf2.financeiro.model;

public enum TipoLancamento {

	RECEITA("Receita"),
	DESPESA("Despesa");
	
	private String descricao;
	
	TipoLancamento(String descricao) {
		this.descricao = descricao;
	}
	
	public String getDescricao() {
		return this.descricao;
	}
	
}

curso-desenvolvimento-web-com-jsf2-master/curso-desenvolvimento-web-com-jsf2-master/ProjetoCursoConfigurandoJPAHibernate/src/com/algaworks/cursojsf2/financeiro/view/CadastroLancamentoBean.java
package com.algaworks.cursojsf2.financeiro.view;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.ValueChangeEvent;

import com.algaworks.cursojsf2.financeiro.model.Lancamento;
import com.algaworks.cursojsf2.financeiro.model.Pessoa;
import com.algaworks.cursojsf2.financeiro.model.TipoLancamento;
import com.algaworks.cursojsf2.financeiro.service.GestaoPessoas;

@ManagedBean
@ViewScoped
public class CadastroLancamentoBean implements Serializable {

	private List<Pessoa> pessoas = new ArrayList<Pessoa>();
	private Lancamento lancamento = new Lancamento();

	@PostConstruct
	public void init() {
		GestaoPessoas gestaoPessoas = new GestaoPessoas();
		this.pessoas = gestaoPessoas.listarTodas();
	}
	
	public void lancamentoPagoModificado(ValueChangeEvent event) {
		this.lancamento.setPago((Boolean) event.getNewValue());
		this.lancamento.setDataPagamento(null);
		FacesContext.getCurrentInstance().renderResponse();
	}
	
	public void cadastrar() {
		System.out.println("Tipo: " + this.lancamento.getTipo());
		System.out.println("Pessoa: " + this.lancamento.getPessoa().getNome());
		System.out.println("Descrição: " + this.lancamento.getDescricao());
		System.out.println("Valor: " + this.lancamento.getValor());
		System.out.println("Data vencimento: " + this.lancamento.getDataVencimento());
		System.out.println("Conta paga: " + this.lancamento.isPago());
		System.out.println("Data pagamento: " + this.lancamento.getDataPagamento());

		this.lancamento = new Lancamento();
		
		String msg = "Cadastro efetuado com sucesso!";
		FacesContext.getCurrentInstance().addMessage(null,
				new FacesMessage(FacesMessage.SEVERITY_INFO, msg, msg));
	}
	
	public TipoLancamento[] getTiposLancamentos() {
		return TipoLancamento.values();
	}

	public Lancamento getLancamento() {
		return lancamento;
	}

	public List<Pessoa> getPessoas() {
		return pessoas;
	}
	
}

curso-desenvolvimento-web-com-jsf2-master/curso-desenvolvimento-web-com-jsf2-master/ProjetoCursoConfigurandoJPAHibernate/src/com/algaworks/cursojsf2/financeiro/view/ConsultaLancamentoBean.java
package com.algaworks.cursojsf2.financeiro.view;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;

@ManagedBean
public class ConsultaLancamentoBean implements Serializable {

	private List<String> lancamentos = new ArrayList<String>();
	
	@PostConstruct
	public void inicializar() {
		for (int i = 0; i < 20; i++) {
			lancamentos.add("");
		}
	}

	public List<String> getLancamentos() {
		return lancamentos;
	}
	
}

curso-desenvolvimento-web-com-jsf2-master/curso-desenvolvimento-web-com-jsf2-master/ProjetoCursoConfigurandoJPAHibernate/WebContent/CadastroLancamento.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core">
	<h:head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>Novo lançamento</title>
		
		<h:outputStylesheet library="css" name="sistema.css"/>
	</h:head>
	<h:body>

		<h1>Novo lançamento</h1>

		<h:form id="frm">
		
			<h:button value="Novo" outcome="CadastroLancamento" />
			<h:button value="Consulta" outcome="ConsultaLancamento" />

			<h:messages showDetail="false" showSummary="true" 
				styleClass="form-messages" errorClass="error"
				infoClass="info" />

			<h:panelGrid columns="2" styleClass="form-grid"
					columnClasses="label, campo">
			
				<h:outputLabel value="Tipo"/>
				<h:selectOneRadio value="#{cadastroLancamentoBean.lancamento.tipo}"
						required="true" label="Tipo do lançamento">
					<f:selectItems value="#{cadastroLancamentoBean.tiposLancamentos}"
						var="tipoLancamento" itemLabel="#{tipoLancamento.descricao}"
						itemValue="#{tipoLancamento}" />
				</h:selectOneRadio>
				
				<h:outputLabel value="Pessoa"/>
				<h:selectOneMenu value="#{cadastroLancamentoBean.lancamento.pessoa}"
						required="true" label="Pessoa">
					<f:selectItem itemLabel="Selecione" noSelectionOption="true" />
					<f:selectItems value="#{cadastroLancamentoBean.pessoas}"
						var="pessoa" itemValue="#{pessoa}" itemLabel="#{pessoa.nome}"/>
				</h:selectOneMenu>
				
				<h:outputLabel value="Descrição"/>
				<h:inputText size="60" value="#{cadastroLancamentoBean.lancamento.descricao}" 
					required="true" label="Descrição" />
				
				<h:outputLabel value="Valor"/>
				<h:inputText size="12" value="#{cadastroLancamentoBean.lancamento.valor}" 
					required="true" label="Valor">
					<f:convertNumber locale="pt_BR" maxFractionDigits="2" minFractionDigits="2" />
					<f:validateDoubleRange minimum="0" />
				</h:inputText>
				
				<h:outputLabel value="Data de vencimento" />
				<h:inputText size="12" value="#{cadastroLancamentoBean.lancamento.dataVencimento}" 
					required="true" label="Data de vencimento">
					<f:convertDateTime pattern="dd/MM/yyyy" />
				</h:inputText>
				
				<h:outputLabel/>
				<h:panelGroup>
					<h:selectBooleanCheckbox id="pagoCheckbox" value="#{cadastroLancamentoBean.lancamento.pago}"
						immediate="true" valueChangeListener="#{cadastroLancamentoBean.lancamentoPagoModificado}" 
						onchange="submit();"/>
					<h:outputLabel value="Conta paga" for="pagoCheckbox"/>
				</h:panelGroup>
				
				<h:outputLabel value="Data de pagamento" rendered="#{cadastroLancamentoBean.lancamento.pago}"/>
				<h:inputText size="12" value="#{cadastroLancamentoBean.lancamento.dataPagamento}" 
						label="Data de pagamento"
						rendered="#{cadastroLancamentoBean.lancamento.pago}">
					<f:convertDateTime pattern="dd/MM/yyyy" />
					<f:validator validatorId="com.algaworks.RequeridoCondicional"/>
					<f:validator validatorId="com.algaworks.DataFutura"/>
					<f:attribute name="checado" value="#{cadastroLancamentoBean.lancamento.pago}"/>
				</h:inputText>
				
				<h:outputLabel/>
				<h:commandButton value="Cadastrar" action="#{cadastroLancamentoBean.cadastrar}" />
			</h:panelGrid>
			
		</h:form>
	</h:body>
</html>

curso-desenvolvimento-web-com-jsf2-master/curso-desenvolvimento-web-com-jsf2-master/ProjetoCursoConfigurandoJPAHibernate/WebContent/ConsultaLancamento.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core">
	<h:head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>Lançamentos</title>
		
		<h:outputStylesheet library="css" name="sistema.css"/>
		<h:outputStylesheet library="css" name="consulta-lancamentos.css"/>
	</h:head>
	<h:body>

		<h1>Lançamentos</h1>

		<h:form id="frm">
			<h:button value="Novo lançamento" outcome="CadastroLancamento" />

			<h:dataTable var="lancamento" value="#{consultaLancamentoBean.lancamentos}"
				width="100%" styleClass="grid" headerClass="cabecalho" rowClasses="cor-sim, cor-nao"
				columnClasses="tipo, pessoa, descricao, valor, vencimento, pagamento, situacao, acoes">
				
				<h:column>
					<h:graphicImage value="/imagens/despesa.png"/>
				</h:column>
				
				<h:column>
					<f:facet name="header">
						Pessoa
					</f:facet>
					
					<h:outputText value="Escola Infantil Abelha Amarela"/>
				</h:column>
				
				<h:column>
					<f:facet name="header">
						Descrição
					</f:facet>
					
					<h:outputText value="Escola filhos"/>
				</h:column>
				
				<h:column>
					<f:facet name="header">
						Valor
					</f:facet>
				
					<h:outputText value="R$ 720,00" styleClass="despesa" />
				</h:column>
			
				<h:column>
					<f:facet name="header">
						Vencimento
					</f:facet>
					
					<h:outputText value="02/07/2012"/>
				</h:column>
				
				<h:column>
					<f:facet name="header">
						Pagamento
					</f:facet>
					
					<h:outputText value="02/07/2012"/>
				</h:column>
				
				<h:column>
					<f:facet name="header">
						Situação
					</f:facet>
					
					<h:outputText value="Pago" />
				</h:column>
				
				<h:column>
					<h:graphicImage value="/imagens/editar.png"/>
					<h:graphicImage value="/imagens/excluir.png"/>
				</h:column>
			</h:dataTable>
		</h:form>
	</h:body>
</html>