curso-jsf-primefaces-essencial-master/curso-jsf-primefaces-essencial-master/componentes-ricos-com-primefaces/src/main/java/com/algaworks/erp/model/Empresa.java
package com.algaworks.erp.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table(name = "empresa")
public class Empresa implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
	
	@Column(name = "nome_fantasia", nullable = false, length = 80)
	private String nomeFantasia;
	
	@Column(name = "razao_social", nullable = false, length = 120)
	private String razaoSocial;
	
	@Column(nullable = false, length = 18)
	private String cnpj;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "data_fundacao")
	private Date dataFundacao;
	
	@ManyToOne
	@JoinColumn(name = "ramo_atividade_id", nullable = false)
	private RamoAtividade ramoAtividade;
	
	@Enumerated(EnumType.STRING)
	@Column(nullable = false, length = 30)
	private TipoEmpresa tipo;
	
	@Column(precision = 10, scale = 2)
	private BigDecimal faturamento;
	
	public BigDecimal getFaturamento() {
        return faturamento;
    }
	
	public void setFaturamento(BigDecimal faturamento) {
        this.faturamento = faturamento;
    }

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNomeFantasia() {
		return nomeFantasia;
	}

	public void setNomeFantasia(String nomeFantasia) {
		this.nomeFantasia = nomeFantasia;
	}

	public String getRazaoSocial() {
		return razaoSocial;
	}

	public void setRazaoSocial(String razaoSocial) {
		this.razaoSocial = razaoSocial;
	}

	public String getCnpj() {
		return cnpj;
	}

	public void setCnpj(String cnpj) {
		this.cnpj = cnpj;
	}

	public Date getDataFundacao() {
		return dataFundacao;
	}

	public void setDataFundacao(Date dataFundacao) {
		this.dataFundacao = dataFundacao;
	}

	public RamoAtividade getRamoAtividade() {
		return ramoAtividade;
	}

	public void setRamoAtividade(RamoAtividade ramoAtividade) {
		this.ramoAtividade = ramoAtividade;
	}

	public TipoEmpresa getTipo() {
		return tipo;
	}

	public void setTipo(TipoEmpresa tipo) {
		this.tipo = tipo;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Empresa other = (Empresa) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Empresa [id=" + id + "]";
	}	
}

curso-jsf-primefaces-essencial-master/curso-jsf-primefaces-essencial-master/componentes-ricos-com-primefaces/src/main/java/com/algaworks/erp/model/RamoAtividade.java
package com.algaworks.erp.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "ramo_atividade")
public class RamoAtividade implements Serializable {

	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
	
	@Column(nullable = false, length = 80)
	private String descricao;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		RamoAtividade other = (RamoAtividade) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "RamoAtividade [id=" + id + "]";
	}
}

curso-jsf-primefaces-essencial-master/curso-jsf-primefaces-essencial-master/componentes-ricos-com-primefaces/src/main/java/com/algaworks/erp/model/TipoEmpresa.java
package com.algaworks.erp.model;

public enum TipoEmpresa {
	
	MEI("Microempreendedor Individual"), 
	EIRELI("Empresa Individual de Responsabilidade Limitada"),
	LTDA("Sociedade Limitada"),
	SA("Sociedade Anônima");
	
	private String descricao;

	TipoEmpresa(String descricao) {
		this.descricao = descricao;
	}
	
	public String getDescricao() {
		return descricao;
	}

}

curso-jsf-primefaces-essencial-master/curso-jsf-primefaces-essencial-master/componentes-ricos-com-primefaces/src/main/java/com/algaworks/erp/controller/GestaoEmpresasBean.java
package com.algaworks.erp.controller;

import java.io.Serializable;

import javax.faces.view.ViewScoped;
import javax.inject.Named;

import com.algaworks.erp.model.Empresa;
import com.algaworks.erp.model.TipoEmpresa;

@Named
@ViewScoped
public class GestaoEmpresasBean implements Serializable {

    private static final long serialVersionUID = 1L;
    
    private Empresa empresa = new Empresa();
    
    public void salvar() {
        System.out.println("Razão social: " + empresa.getRazaoSocial()
                + " - Nome fantasia: " + empresa.getNomeFantasia()
                + " - Tipo: " + empresa.getTipo());
    }
    
    public String ajuda() {
        return "AjudaGestaoEmpresas?faces-redirect=true";
    }
    
    
    public Empresa getEmpresa() {
        return empresa;
    }
    
    public TipoEmpresa[] getTiposEmpresa() {
        return TipoEmpresa.values();
    }
}

curso-jsf-primefaces-essencial-master/curso-jsf-primefaces-essencial-master/componentes-ricos-com-primefaces/src/main/webapp/AjudaGestaoEmpresas.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
 	xmlns:h="http://xmlns.jcp.org/jsf/html"
 	xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>

<meta charset="UTF-8"/>
<title>Ajuda</title>

<h:outputStylesheet library="algaworks" name="estilo.css" />

</h:head>

<h:body>
	<header>
		<h:graphicImage library="algaworks" name="logo.png" />
	</header>
	
	<h2>Ajuda</h2>

	<div id="conteudo">
		<h:form>
			<p>Esta é a ajuda da página de cadastro de empresas.</p>
			
			<p>
				<h:commandLink value="Voltar" action="GestaoEmpresas?faces-redirect=true" />
			</p>	
		</h:form>	
	</div>
	
	<footer>
		Curso online "JSF e PrimeFaces Essencial"
	</footer>
</h:body>

</html>

curso-jsf-primefaces-essencial-master/curso-jsf-primefaces-essencial-master/componentes-ricos-com-primefaces/src/main/webapp/GestaoEmpresas.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
 	xmlns:h="http://xmlns.jcp.org/jsf/html"
 	xmlns:f="http://xmlns.jcp.org/jsf/core"
 	xmlns:p="http://primefaces.org/ui">
<h:head>

<meta charset="UTF-8"/>
<title>Gestão Empresas</title>

<h:outputStylesheet library="algaworks" name="estilo.css" />

</h:head>

<h:body>
	<header>
		<h:graphicImage library="algaworks" name="logo.png" />
	</header>

	<div id="conteudo">
		<h:form id="formulario">
			<h:panelGrid columns="2">
				<p:outputLabel value="Razão social: " for="razaoSocial" />
				<h:panelGroup>
					<p:inputText id="razaoSocial" value="#{gestaoEmpresasBean.empresa.razaoSocial}" required="true" />
					
					<p:message for="razaoSocial"/>
				</h:panelGroup>
				
				<p:outputLabel value="Nome fantasia: " for="nomeFantasia" />
				<p:inputText id="nomeFantasia" value="#{gestaoEmpresasBean.empresa.nomeFantasia}" />
				
				<p:outputLabel value="Tipo empresa" for="tipo" />
				<h:panelGroup>
					<p:selectOneMenu id="tipo" value="#{gestaoEmpresasBean.empresa.tipo}" required="true">
						<f:selectItem itemLabel="Selecione..." />
						<f:selectItems value="#{gestaoEmpresasBean.tiposEmpresa}"
							var="tipoEmpresa" itemLabel="#{tipoEmpresa.descricao}" itemValue="#{tipoEmpresa}" />
					</p:selectOneMenu>
					
					<p:message for="tipo"/>
				</h:panelGroup>
				
				<p:outputLabel value="CNPJ: " for="cnpj" />
				<h:panelGroup>
					<p:inputText id="cnpj" value="#{gestaoEmpresasBean.empresa.cnpj}"
							label="CNPJ">
						<f:validateLength minimum="18" maximum="18" />	
					</p:inputText>
					
					<p:message for="cnpj"/>
				</h:panelGroup>
				
				<p:outputLabel value="Data fundação: " for="dataFundacao" />
				<h:panelGroup>
					<p:inputText id="dataFundacao" value="#{gestaoEmpresasBean.empresa.dataFundacao}"
							label="Data fundação">
						<f:convertDateTime pattern="dd/MM/yyyy" />	
					</p:inputText>
					
					<p:message for="dataFundacao"/>
				</h:panelGroup>
				
				<p:outputLabel value="Faturamento: " for="faturamento" />
				<h:panelGroup>
					<p:inputText id="faturamento" value="#{gestaoEmpresasBean.empresa.faturamento}"
							label="Faturamento">
						<f:convertNumber pattern="#,##0.00" />
						<f:validateDoubleRange minimum="0" />
					</p:inputText>
					
					<p:message for="faturamento"/>				
				</h:panelGroup>
				
				<h:outputLabel />
				<p:commandButton value="Salvar" actionListener="#{gestaoEmpresasBean.salvar}"
						update="@form"/>
				
				<h:outputLabel />
				<p:commandLink value="Ajuda?" action="#{gestaoEmpresasBean.ajuda}"/>
			</h:panelGrid>
			
			<p:dataTable value="#{[0, 0, 0, 0]}">
				<p:column headerText="Razão social">					
					<h:outputText value="AlgaWorks Softwares, Treinamentos LDTA" />
				</p:column>
				
				<p:column headerText="Nome fantasia">
					<h:outputText value="AlgaWorks" />
				</p:column>
				
				<p:column headerText="Tipo empresa">
					<h:outputText value="LDTA" />
				</p:column>
			</p:dataTable>
		</h:form>	
	</div>
	
	<footer>
		Curso online "JSF e PrimeFaces Essencial"
	</footer>
</h:body>

</html>